project:
  type: website

website:
  title: "AsiaR Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/AsiaR-community
      - icon: twitter
        href: https://twitter.com/AsiaR_comm
format:
  html:
    theme: cosmo
    css: styles.css



